### ISSUE TITLE
Alternate Java-Name for Group Interfaces

### ISSUE THREAD

**Issue by techteam-bln** [mklemm/jaxb-rich-contract-plugin#45]
My schema an  xml files use UPPER_SNAKE_CASE for all elements and attributes e.g.:
<CAR>
  <ENGINE_ELE> ... </ENGINE_ELE>
</CAR>

On elements which will be classes or properties it is possible to define an alternate java name over the jaxb:class / jaxb:property - annotations.
For groups it seems it is not possible on jaxb.

Is it possible to add an appinfo annotation for your group plugin?

I don't like Java interfaces like "LOCATION.class" ;)

**Comment by mklemm** [comment]
Would certainly be possible, but maybe a ClassNameTransformer could also be introduced.
For 4.2.0, I am planning a complete overhaul of group-interfaces, since it isn't very robust wrt possible build configurations.

**Comment by mklemm** [comment]
A quick fix for this issue has just been pushed, but it's not nice... I thought it would be possible to apply a customization directly on the group or attributeGroup XSD definition in the same way as we can apply <jxb:class... on complexTypes, but this isn't possible because XJC consumes customizations on group and attributeGroup definitions in the context of the complexType that uses them even before any plugin gets a chance to see them, and so they are rejected as unused.
Workaround is: We apply a global customization on the schema level that we give the groupName that they apply to. Not nice, but seems to work for now.
